name: Firebase Functions Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build And Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      - uses: actions/checkout@master
      - name: setup ubuntu
        run: sudo apt-get --quiet update --yes
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        working-directory: ./functions
        run: |
          yarn install
      - name: Register .env
        working-directory: ./functions
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
          ASANA_CLIENT_ID: ${{ secrets.ASANA_CLIENT_ID }}
          ASANA_CLIENT_SECRET: ${{ secrets.ASANA_CLIENT_SECRET }}
        run: |
          echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}" >> ./.env
          echo "GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}" >> ./.env
          echo "GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}" >> ./.env
          echo "GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}" >> ./.env
          echo "GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}" >> ./.env
          echo "ASANA_CLIENT_ID=${ASANA_CLIENT_ID}" >> ./.env
          echo "ASANA_CLIENT_SECRET=${ASANA_CLIENT_SECRET}" >> ./.env
      - name: yarn build
        working-directory: ./functions
        run: |
          yarn run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./functions
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./functions/dist